apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: thetips4you/nodeapp:latest
        resources:
            limits:
              memory: 300Mi
              cpu: 100m
            requests:
              memory: 300Mi
              cpu: 100m
        
        ports:
        - containerPort: 3000
